site_name: homelab
repo_url: https://github.com/JohnFodero/homelab
theme:
  name: material
  features:
    - navigation.footer
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - toc.integrate
    - navigation.top
    - icons
    - emoji
  language: en

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/john-fodero/
    - icon: fontawesome/brands/github
      link: https://github.com/JohnFodero

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg