apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-deployment
  labels:
        app: mqtt-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-app
  template:
    metadata:
      labels:
        app: mqtt-app
    spec:
      containers:
      - name: broker-container
        image: hivemq/hivemq-ce
        resources:
          limits:
            memory: "0.6Gi"
            cpu: "300m"  
          requests:
            memory: "0.2Gi"
            cpu: "150m"  
        ports:
        - containerPort: 1883