---
- name: Prepare k3s nodes
  hosts: k3scluster
  gather_facts: yes
  environment: "{{ proxy_env | default({}) }}"
  roles:
    - role: prereq
      become: true
    - role: download
      become: true
    - role: raspberrypi
      become: true

- name: Setup k3s servers
  hosts: k3smaster
  environment: "{{ proxy_env | default({}) }}"
  roles:
    - role: k3s_server
      become: true

- name: Setup k3s agents
  hosts: k3snodes
  environment: "{{ proxy_env | default({}) }}"
  roles:
    - role: k3s_agent
      become: true

- name: Configure k3s cluster
  hosts: k3smaster
  environment: "{{ proxy_env | default({}) }}"
  roles:
    - role: k3s_server_post
      become: true