name: pr 
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: rojopolis/spellcheck-github-actions@0.35.0
      name: Spellcheck
      with:
        task_name: Markdown
        output_file: spellcheck-output.txt
    - uses: actions/upload-artifact@v3
      if: '!cancelled()'
      with:
        name: Spellcheck Output
        path: spellcheck-output.txt
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: check manifests
      uses: hermanbanken/kubeconform-action@v1
      with:
        options: ["-summary", "-output", "json", "fixtures/invalid.yaml"]